name: client
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.1.0
  flutter_riverpod: ^2.3.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  uuid: ^3.0.7
  api_client:
    path: ../api_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
