name: server
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  api_client:
    path: ../api_client
  uuid: ^3.0.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
